### ISSUE TITLE
Addon is not working at all

### ISSUE THREAD

**Issue by Fed03** [poteto/ember-cli-flash#1]
Hi,
I'm trying to use this addon inside my project built with ember-cli 0.1.11, but when I `serve` the development application this is what happens

```
File: ember-cli-flash/components/flash-message
Unexpected token (3:20)
SyntaxError: Unexpected token (3:20)
    at raise (D:\Work\ember-cli-flash-modal\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\acorn.js:333:15)
    at unexpected (D:\Work\ember-cli-flash-modal\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\acorn.js:1366:5)
    at parseIdent (D:\Work\ember-cli-flash-modal\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\acorn.js:2471:7)
    at parsePropertyName (D:\Work\ember-cli-flash-modal\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\acorn.js:2250:78)
```

and so on... the problem is obviously the Destructors....
Let me know if you need more infos

**Comment by poteto** [comment]
Hey, sorry about this. It's a known [issue](https://github.com/ember-cli/ember-cli/issues/3174) with ember-cli addons, just waiting on a bugfix to be pushed shortly. If one isn't pushed this week I'll change everything back to es5

**Comment by poteto** [comment]
@Fed03 I decided to push a hotfix temporarily until the bugfix is live, try this: https://github.com/poteto/ember-cli-flash/releases/tag/0.1.3
