### ISSUE TITLE
Unit test fails with error at Array.reduce

### ISSUE THREAD

**Issue by pogopaule** [poteto/ember-cli-flash#100]
Hi! Following the instructions on how to write unit tests, I get the following error running one:

My Code:
```
beforeEach() {
  this.container.lookup('service:flash-messages').registerTypes(['success', 'warning']);
}

```

```
TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at get (http://192.168.77.6:4200/assets/vendor.js:107066:45)
    at Descriptor.ComputedPropertyPrototype.get (http://192.168.77.6:4200/assets/vendor.js:24630:26)
    at get (http://192.168.77.6:4200/assets/vendor.js:30476:19)
    at null._setInitialState (http://192.168.77.6:4200/assets/vendor.js:106678:49)
    at Object.sendEvent (http://192.168.77.6:4200/assets/vendor.js:26846:25)
    at new Class (http://192.168.77.6:4200/assets/vendor.js:47853:25)
    at Function.ClassMixinProps.create (http://192.168.77.6:4200/assets/vendor.js:48274:14)
    at _newFlashMessage (http://192.168.77.6:4200/assets/vendor.js:106777:38)
    at add (http://192.168.77.6:4200/assets/vendor.js:106732:24)
```

**Comment by cantsin** [comment]
I recently got this error, too. I ended up working around this by adding

```flashMessages: {
  danger: Ember.K
}```

to the test subject. I'm using version `1.3.8`.

**Comment by poteto** [comment]
Will dig into this, thanks for reporting

**Comment by Fryie** [comment]
I had this same issue. It turned out in my case that my test helper was not set up correctly.

It was saying
```
FlashObject.reopen({ _destroyLater: null });
```
which apparently comes from an old version of this addon.

I changed this to
```
FlashObject.reopen({ setInitialState: null });
```
which is from version 1.3.4 that I'm using. If on a newer version, the code should probably be changed to reflect the current blueprint which is again somewhat different.

**Comment by sbatson5** [comment]
The unit test instructions were updated in: https://github.com/poteto/ember-cli-flash/pull/137

`container.lookup` is deprecated in favor of `getOwner`. @poteto Good to close?
