### ISSUE TITLE
Installation crashes with: [ember-cli-version-checker] 'checker.forEmber' has been removed, please use 'checker.for(`ember-source`)'

### ISSUE THREAD

**Issue by lolmaus** [poteto/ember-cli-flash#340]
`ember i ember-cli-flash` yields this:

```
  - stack: Error: [ember-cli-version-checker] 'checker.forEmber' has been removed, please use 'checker.for(`ember-source`)'
    at VersionChecker.forEmber (C:\Code\kaliber5\test-app\node_modules\ember-cli-version-checker\src\version-checker.js:26:11)
    at Class.afterInstall (C:\Code\kaliber5\test-app\node_modules\ember-cli-flash\blueprints\ember-cli-flash\index.js:14:25)
...
```

**Comment by lolmaus** [comment]
Adding this to host app's `package.json` resolves the issue:

```js
  "resolutions": {
    "ember-cli-version-checker": "^4.0.0"
  }
```

It's fun how `ember-cli-version-checker` does not mention the deprecation and removal of `forEmber`. 😒 

I've started an upsteram issue: https://github.com/ember-cli/ember-cli-version-checker/issues/237

**Comment by lolmaus** [comment]
CC @simonihmig.
